import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { Script, createContext } from 'node:vm';

const root = process.cwd();
const websiteDir = join(root, 'ui_kits', 'website');
const outFile = join(websiteDir, 'dist', 'site.js');
const babelFile = join(process.env.TEMP || process.env.TMP || '.', 'babel-standalone-7.29.0.js');

if (!existsSync(babelFile)) {
  throw new Error(`Missing Babel standalone at ${babelFile}. Download it before running this script.`);
}

const sourceFiles = [
  'tweaks-panel.jsx',
  'HeroGraphics.jsx',
  'Header.jsx',
  'Sections.jsx',
  'Features.jsx',
  'Pricing.jsx',
  'Footer.jsx',
  'App.jsx',
  'Tweaks.jsx',
];

const source = [
  '/*',
  ' * Generated by tools/build-website.mjs.',
  ' * Edit the JSX source files in ui_kits/website, then rebuild this bundle.',
  ' */',
  ...sourceFiles.map(file => `\n// ${file}\n${readFileSync(join(websiteDir, file), 'utf8')}`),
].join('\n');

const context = {
  console,
  setTimeout,
  clearTimeout,
  setInterval,
  clearInterval,
};
createContext(context);
new Script(readFileSync(babelFile, 'utf8'), { filename: 'babel-standalone.js' }).runInContext(context);

const result = context.Babel.transform(source, {
  presets: ['react'],
  comments: false,
  compact: false,
});

writeFileSync(outFile, result.code, 'utf8');
console.log(`Built ${outFile}`);
